Helm chart Version upgrade
cloud-native-toolkit/terraform-gitops-sonarqube pull request #26
Opened 2022-06-21 05:44 UTC by RamyaRaghuveera

Signed-off-by: Ramya Raghuveera <ramragh1@in.ibm.com>

2022-07-13 12:22 UTC, seansund requested changes
Need to move off of deprecated helm registry

2022-07-13 12:22 UTC, seansund commented on chart/sonarqube/Chart.yaml
>      repository: https://oteemo.github.io/charts
This helm registry has been deprecated. We need to move to the SonarSource version - https://github.com/SonarSource/helm-chart-sonarqube/tree/master/charts/sonarqube . Their latest helm chart is v4.0.3 . The chart is based on the Oteemo chart we have been using so hopefully the migration is straight-forward

2022-07-16 14:59 UTC, RamyaRaghuveera commented
@seansund I have done the requested changes. Could you please have a look and approve.

2022-07-28 13:06 UTC, seansund requested changes
One change

2022-07-28 13:06 UTC, seansund commented on variables.tf
> +variable "PostgresConfigmap" {
The variable name should follow the format convention of all the other variables - postgres_configmap

2022-07-28 13:11 UTC, seansund requested changes
one more change

2022-07-28 13:11 UTC, seansund commented on .github/scripts/validate-deploy.sh
> +kubectl rollout status "statefulset/"${STATEFULSET} -n "${NAMESPACE}" || exit 1
This can be replaced with a call to `check_k8s_resource "${NAMESPACE}" statefulset "${STATEFULSET}"`

2022-07-28 16:25 UTC, RamyaRaghuveera commented
@seansund I have done the requested changes. Could you please approve.

2022-08-01 14:08 UTC, seansund approved these changes
lgtm

2022-08-01 14:45 UTC, merged